[project]
org-name = "ballerinax"
version = "0.2.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["pagerduty", "client", "connector", "ballerina"]
repository = "https://github.com/ballerina-platform/module-ballerinax-pagerduty"
