name: Deployment

on:
  release:
    types: [published]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@master
              with:
                  args:
                      build -a -c
              env:
                  PAGERDUTY_API_TOKEN: ${{ secrets.PAGERDUTY_API_TOKEN }}
                                   
            - name: Ballerina Push
              uses: ballerina-platform/ballerina-action/@master
              with:
                  args:
                      push -a
              env:
                  BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
